{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/srcsim.json"}, "html": {"href": "#!/osrf/srcsim"}, "avatar": {"href": "data/bytebucket.org/ravatar/{c41021d9-0217-4628-999d-7f8d82f98dcb}ts=c_plus_plus"}}, "type": "repository", "name": "srcsim", "full_name": "osrf/srcsim", "uuid": "{c41021d9-0217-4628-999d-7f8d82f98dcb}"}, "links": {"attachments": {"href": "data/repositories/osrf/srcsim/issues/57/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/srcsim/issues/57.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/srcsim/issues/57/watch"}, "comments": {"href": "data/repositories/osrf/srcsim/issues/57/comments_page=1.json"}, "html": {"href": "#!/osrf/srcsim/issues/57/rospy-init_node-does-work-second-time"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/srcsim/issues/57/vote"}}, "reporter": {"display_name": "mocorobo", "uuid": "{0e09769a-52a9-4036-891c-9b58d9c43401}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B0e09769a-52a9-4036-891c-9b58d9c43401%7D"}, "html": {"href": "https://bitbucket.org/%7B0e09769a-52a9-4036-891c-9b58d9c43401%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/41014f87d0be5e02393531e702539c82d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsM-1.png"}}, "nickname": "mocorobo", "type": "user", "account_id": "557058:91d63c8e-a67c-4dad-a84a-75eca07d4807"}, "title": "rospy init_node does work second time through", "component": null, "votes": 0, "watches": 1, "content": {"raw": "I \"rospy.signal _shutdown()\", cleanup(), etc. While the node disappears from the rosnode list list, it is still around and a second rospy.init_node call fails.\r\n\r\nI am trying to automate my simulations and this is a magor bug I assume in ROS.  If I try running roscore first and just one rospy.node_init)(), I get a flood of TF_OLD_DATA warnings at subsequent roslaunches as some internal data has the last simulations timing data.\r\n\r\nSeems there should be a way to run multiple simulations sequentially.", "markup": "markdown", "html": "<p>I \"rospy.signal _shutdown()\", cleanup(), etc. While the node disappears from the rosnode list list, it is still around and a second rospy.init_node call fails.</p>\n<p>I am trying to automate my simulations and this is a magor bug I assume in ROS.  If I try running roscore first and just one rospy.node_init)(), I get a flood of TF_OLD_DATA warnings at subsequent roslaunches as some internal data has the last simulations timing data.</p>\n<p>Seems there should be a way to run multiple simulations sequentially.</p>", "type": "rendered"}, "assignee": null, "state": "closed", "version": null, "edited_on": null, "created_on": "2016-12-19T19:31:46.475690+00:00", "milestone": null, "updated_on": "2017-03-08T17:20:33.914558+00:00", "type": "issue", "id": 57}