{"links": {"self": {"href": "data/repositories/osrf/srcsim/issues/216/comments/37380422.json"}, "html": {"href": "#!/osrf/srcsim/issues/216#comment-37380422"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/srcsim/issues/216.json"}}, "type": "issue", "id": 216, "repository": {"links": {"self": {"href": "data/repositories/osrf/srcsim.json"}, "html": {"href": "#!/osrf/srcsim"}, "avatar": {"href": "data/bytebucket.org/ravatar/{c41021d9-0217-4628-999d-7f8d82f98dcb}ts=c_plus_plus"}}, "type": "repository", "name": "srcsim", "full_name": "osrf/srcsim", "uuid": "{c41021d9-0217-4628-999d-7f8d82f98dcb}"}, "title": "Task 3 checkpoint 4 does not complete"}, "content": {"raw": "I'm pretty sure this happens only in task3 only worlds.  I think a full world would not have this problem.  I was on route to testing that this morning when I knocked Val over and had to go to work :-).", "markup": "markdown", "html": "<p>I'm pretty sure this happens only in task3 only worlds.  I think a full world would not have this problem.  I was on route to testing that this morning when I knocked Val over and had to go to work :-).</p>", "type": "rendered"}, "created_on": "2017-06-05T15:10:16.047499+00:00", "user": {"display_name": "Jeremy White", "uuid": "{abab48b0-35b1-4102-8373-e88a492c5294}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Babab48b0-35b1-4102-8373-e88a492c5294%7D"}, "html": {"href": "https://bitbucket.org/%7Babab48b0-35b1-4102-8373-e88a492c5294%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/2764d3b5adf560de71f57e48a30550bad=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJW-3.png"}}, "nickname": "knitfoo", "type": "user", "account_id": "557058:5de786d6-615c-44ef-8e12-f079efa38357"}, "updated_on": null, "type": "issue_comment", "id": 37380422}